version: '3.8'

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-runner-1
    environment:
      RUNNER_TOKEN: $RUNNER_TOKEN
      RUNNER_NAME: $RUNNER_NAME
      RUNNER_LABELS: $RUNNER_LABELS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # allow use Docker inside the runner
      - runner-work:/home/runner/_work
    restart: unless-stopped
    networks:
      - github-runner-network

volumes:
  runner-work:

networks:
  github-runner-network:
    driver: bridge